### ISSUE TITLE
[Vapor3] Auth password not applied

### ISSUE THREAD

**Issue by patrick-zippenfenig** [vapor/redis#105]
I just tried to use a redis password and I suspect the auth command never gets executed
https://github.com/vapor/redis/blob/master/Sources/Redis/Database/RedisDatabase.swift#L27

The auth command future is created, but (if I understand event loops correctly) never executed

**Comment by pedantix** [comment]
hi! I will look into figuring this out and testing this issue away. Thank you for your patience!

**Comment by patrick-zippenfenig** [comment]
Thanks!
