### ISSUE TITLE
SADD Integer Rejection

### ISSUE THREAD

**Issue by Mordil** [vapor/redis#127]
When executing the `SADD` command with a `RedisData(integerLiteral:)` Redis throws the error: `ERR Protocol error: expected '$', got ':'`

The rejected stream input:
`"*3\r\n$9\r\nSISMEMBER\r\n$30\r\nGSAPI_GEOFENCING_ON_SITE_COUNT\r\n:31\r\n"`

If I use `RedisData(stringLiteral:)` instead, Redis accepts the stream.

Accepted stream input::
`"*3\r\n$9\r\nSISMEMBER\r\n$30\r\nGSAPI_GEOFENCING_ON_SITE_COUNT\r\n$2\r\n31\r\n"`

**Comment by John-Connolly** [comment]
All Redis commands need to be sent as BulkStrings

**Comment by Mordil** [comment]
Most cases of learning this will be solved with #131 being merged.
