### ISSUE TITLE
`LPUSH` and `RPOP` prints errors

### ISSUE THREAD

**Issue by mcdappdev** [vapor/redis#132]
`conn.lpush([data], into: key)` prints `[WARNING] [Async] [QueueHandler] Read triggered when input queue was empty, ignoring: RedisData(storage: Redis.RedisData.Storage.integer(1)).`

`conn.rpop(key)` prints `[WARNING] [Async] [QueueHandler] Read triggered when input queue was empty, ignoring: RedisData(storage: Redis.RedisData.Storage.bulkString(125 bytes)).`

**Comment by vzsg** [comment]
Is this still a thing? Because I can't seem to be able to reproduce it in a test.

**Comment by mcdappdev** [comment]
Maybe it's just how I was doing it, you can see the implementation here: https://github.com/vapor-community/redis-jobs/blob/master/Sources/RedisJobs/RedisJobs.swift#L45

**Comment by tanner0101** [comment]
This was resolved in https://github.com/vapor/redis/releases/tag/3.0.3
