### ISSUE TITLE
add more complex methods for ordered sets and others

### ISSUE THREAD

**Issue by ericchapman** [vapor/redis#137]
Hey @tanner0101,

I am implementing allot of the more complex methods such as the "z" items and things lke that.  Are you interested in bringing these into the overall repo, or are you trying to keep the repo "simple".

I will happily submit a PR if you are interested.

Thanks
Eric

**Comment by tanner0101** [comment]
@ericchapman i'm happy to accept any convenience methods for Redis commands here. :)

**Comment by ericchapman** [comment]
Adde PR here.  I will add more over time as needed.  Thought about adding all of the Z ones but there are ALLOT.

https://github.com/vapor/redis/pull/138
