### ISSUE TITLE
redis.command not working properly - works only with INFO

### ISSUE THREAD

**Issue by gurugeek** [vapor/redis#154]
```
    
    router.get("redis") { req -> Future<String> in
        return req.withNewConnection(to: .redis) { redis in
          
            // send INFO command to redis
            let query = "SELECT 2"
            print (query)
            
            return redis.command(query)
                // map the resulting RedisData to a String
                .map { $0.string ?? "" }
        }
    }
    
```
return
{"error":true,"reason":"ERR unknown command `SELECT 2`, with args beginning with: "}

other commands like KEYS * or SCAN also fail. The only command that works is INFO as per tutorial. Is this the intend behaviour ?

**Comment by tanner0101** [comment]
You need to send `SELECT 2` as `["SELECT", "2"]`. You can do that by passing the `2` in an array to the second argument of `command`
