### ISSUE TITLE
Redis should provide a Application.Sessions.Provider

### ISSUE THREAD

**Issue by 0xTim** [vapor/redis#162]
This is missing from the Vapor 3 migration. There should be a Redis equivalent of https://github.com/vapor/fluent/blob/master/Sources/Fluent/Fluent%2BSessions.swift

**Comment by Mordil** [comment]
This is now available in [4.0.0-rc.1.1](https://github.com/vapor/redis/releases/tag/4.0.0-rc.1.1)
