### ISSUE TITLE
PubSub not work with redis 4.1.0

### ISSUE THREAD

**Issue by gulivero1773** [vapor/redis#185]
### To Reproduce

1. Add package with configuration '...'
2. Send request with options When I use app.redis.subscribe(to: "service") { (channel, message) in 
3. No redis found for id default, or the app may not have finished booting. Also, the eventLoop must be from Application's EventLoopGroup.: file Redis/RedisStorage.swift, line 51
2021-02-27 21:25:57.161836+0200 Run[19967:238904] Fatal error: No redis found for id default, or the app may not have finished booting. Also, the eventLoop must be from Application's EventLoopGroup.: file Redis/RedisStorage.swift, line 51

### Environment

* Vapor Framework version: 4.41.1
* Vapor Toolbox version: last
* OS version: 11.2.2

**Comment by 0xTim** [comment]
@gulivero1773 if you add `app.boot()` before you call Redis does that fix it?

**Comment by gulivero1773** [comment]
@0xTim Thank you! It works, but I don’t understand why

**Comment by 0xTim** [comment]
@gulivero1773 Redis now needs the boot function to be called to set up its internal state correctly. Unfortunately this isn't yet documented
