### ISSUE TITLE
Add Key Expiration to Encodable Set

### ISSUE THREAD

**Issue by waltertyree** [vapor/redis#187]
I would like to add a `setex` to `RedisClient+Codable.swift` to enable the user to be able to set their encoded entity with an expiration in one step. Currently it takes two steps as the basic `set` in the extension doesn't support an expiration time.

I have a PR, but the guidelines appear to say I to open an issue first, so I am doing that.

**Comment by 0xTim** [comment]
Yep this seems like a valuable addition
