### ISSUE TITLE
Compiler warning: deprecated version of flatMapThrowing

### ISSUE THREAD

**Issue by sbeitzel** [vapor/redis#195]
### Describe the bug

While building a newly constructed Vapor project, I'm getting a few compiler warnings:
```
RediStack/Sources/RediStack/RESP/RESPValue.swift:187:21: warning: 'flatMapThrowing(file:line:_:)' is deprecated: Please don't pass file:line:, there's no point.
        return self.flatMapThrowing(file: file, line: line) {
```

### Expected behavior

This is a cleanup bug -- someone* ought to go through the source and take care of the deprecations.

* someone might be me, although I can't imagine I'm the first to notice this

### Environment

* Vapor Framework version: 4.54.0
* Vapor Toolbox version: 18.3.3
* OS version: macOS Monterey (12.0.1)
Darwin TellPotentate.local 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:01 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T6000 arm64

**Comment by Mordil** [comment]
Thanks for reporting - this is actually a RediStack issue itself. I've transcribed your bug report into [GitLab as issue #102](https://gitlab.com/Mordil/RediStack/-/issues/102)
