### ISSUE TITLE
Integer Type Conversion

### ISSUE THREAD

**Issue by collinhundley** [vapor/redis#32]
Currently the `toInt()` method only succeeds when Redis returns an explicit `integer` type, prefixed with `:`. This may be expected behavior, but I don't find it particularly useful since most types are returned as `bulk string`.

Would you consider expanding the `toInt()` method to convert `bulk string`s to `Int` as well?

**Comment by czechboy0** [comment]
Sure, I'd accept a PR for that :) If you do so, please add that to simple string as well.

**Comment by collinhundley** [comment]
Will do!

I was going to open another issue, but I might as well ask this here too:  what about adding some kind of support for `Hash`? Of course Redis returns hash values as an array, but perhaps we could add a `toDictionary()` method that returns `[String : AnyObject]`, or something like that. When used in conjunction with `HGETALL`, the keys and values could be extracted in alternating order. For `HMGET` I'm not sure we can do much better than an array, since the keys don't get returned.

**Comment by czechboy0** [comment]
I personally haven't used hashes with redis yet, but what you're describing makes a lot of sense so I'd accept that happily.

**Comment by tanner0101** [comment]
Added in #56
