### ISSUE TITLE
Cannot call commands with more than 1 word

### ISSUE THREAD

**Issue by PuerkitoBio** [vapor/redis#47]
Many redis commands are composed of multiple words, but in `Redbird.swift` there's a validation that the command must be a single word otherwise it's an error (`RedbirdError.moreThanOneWordSpecifiedAsCommand`).

e.g. if you try `client.command("CONFIG GET", params: ["*"])`.

IMO you shouldn't try to validate the command at all, as redis will soon support modules which may define additional commands (currently in the unstable branch), and the config allows to rename known commands to something else (see `rename-command` in https://raw.githubusercontent.com/antirez/redis/3.0/redis.conf). I think you should consider whatever's passed into `command` method to be the command to execute.

**Comment by tanner0101** [comment]
This should be more clear in #56
