### ISSUE TITLE
input was called while inputBuffer is not nil

### ISSUE THREAD

**Issue by shanehsu** [vapor/redis#70]
* OS: macOS High Sierra
* Redis version: 2d150f6ec90b1071a0633272180c4dafc1043f92

### Expected Behavior

Using the `run(command:arguments:)` should succeed!

### Current Behavior

Using the `run(command:arguments:)`, I encountered many such errors. I cannot pin point the exact condition for this to happen since it sometimes work.

```
Fatal error: input was called while inputBuffer is not nil: file /Users/hsupengjun/Projects/Libraries/JARPC-upstream/.build/checkouts/async.git-2335297525913451934/Sources/Async/Socket/SocketSink.swift, line 44
Illegal instruction: 4
```

The code that _could_ cause the error (there are quite some more),

```
_ = client.run(command: "LPUSH", arguments: [.bulkString(target), .bulkString(data)])
_ = client.run(command: "LREM", arguments: [.bulkString(processingQueue), "0", .bulkString(work)])
```

The resolved packages,

```
{
  "package": "Async",
  "repositoryURL": "https://github.com/vapor/async.git",
  "state": {
    "branch": "beta",
    "revision": "e2dec3c2013d5c71e3ebace661344de7d1259b79",
    "version": null
  }
},
{
  "package": "Redis",
  "repositoryURL": "https://github.com/vapor/redis.git",
  "state": {
    "branch": "beta",
    "revision": "2d150f6ec90b1071a0633272180c4dafc1043f92",
    "version": null
  }
},
```

Screenshot of call stack,

<img width="1792" alt="2017-12-22 10 00 50" src="https://user-images.githubusercontent.com/2708084/34300558-9f5d29aa-e763-11e7-91c5-2625eccd4836.png">

---

### How to Reproduce

I actually don't know how. 

If my bug report is malformed or otherwise, please mention me. I can provide exact code through PM in Slack if needed. :)

**Comment by Joannis** [comment]
Reading from your stack trace (and from personal knowledge of your use case) you're not running redis on a Vapor 3 eventloop. I'm almost certain this is the cause of the problem here.

**Comment by shanehsu** [comment]
Correct. But even when the call is async’ed to the same queue which RedisClient is created with, the issue doesn’t go away.

Am I missing something?

**Comment by John-Connolly** [comment]
I think this is a bug that back pressure introduced.  Redis supports multiplexing so we should be able to call a command before the first one returns a result.

**Comment by Joannis** [comment]
@John-Connolly That's not how back pressure works here. Back pressure isn't making a connection non-multiplexed, it prevents further processing when the socket cannot write (such as full write buffers due to slow network connections). But yes, the same bug appeared in MySQL serialiser when writing, which is a non-multiplexed connection. So this must be a TCP write bug, I'm thinking.

**Comment by John-Connolly** [comment]
Okay, that makes sense.
