### ISSUE TITLE
Updating from v1 to v2

### ISSUE THREAD

**Issue by noobiept** [vapor/redis#77]
Hello, so I've been planning on updating an application of mine that used the version 1 of this library to the more recent one, and I'm having some doubts about how to proceed.
It seems that not all of the available redis operations are defined now, for example, how do I convert 'MULTI', 'EXEC', 'HGETALL', etc?

Also, is there any documentation (or blog post, etc) with some examples on the recent version? 
Cheers!

**Comment by tanner0101** [comment]
@noobiept you'll probably want to wait for version 3 which should be coming out soon. As for the operations, those are only convenience functions. Every Redis command that exists (with the exception of SUBSCRIBE) works the exact same way. In other words, if you can do one command, you can do them all.

**Comment by vzsg** [comment]
And to actually do "custom" commands (which are not covered by the convenience functions), you need to use the `custom` case of the Command enum, and do some manual work on extracting the response.

HGETALL for example would look like this:

```
let res = try client.command(.custom("HGETALL".makeBytes()), ["foo"])
// res is an array of strings, every even index is a key, and the odd indexes are values.
print(res?.array?.map { $0?.string })
```

Here's MULTI:
```
try client.command(.custom("MULTI".makeBytes()))
```

And EXEC:

```
let multiRes = try client.command(.custom("EXEC".makeBytes()))
// multiRes is an array of responses or null. Process according to your executed commands.
```

**Comment by noobiept** [comment]
When is version 3 expected to be released? I guess I can wait a bit.

Thanks for the examples, I'll try them out.

**Comment by tanner0101** [comment]
@noobiept soon hopefully.
