### ISSUE TITLE
Add conveniences for common redis commands. 

### ISSUE THREAD

**Issue by John-Connolly** [vapor/redis#87]
### String
- [x] MSET 
- [x] MGET
- [x] INCR
- [x] INCRBY
- [x] DECR
- [x] DECRBY
- [x] DEL

### List
- [x] RPUSH
- [x] LPUSH
- [x] LRANGE
- [x] LINDEX
- [x] LLEN
- [x] LSET
- [x] RPOP
- [x] RPOPLPUSH

### Sets
- [ ] SADD
- [ ] SCARD
- [ ] SREM
- [ ] SISMEMBER
- [ ] SMEMBERS

### Sorted Sets
- [ ] ZADD
- [ ] ZCARD
- [ ] ZCOUNT
- [ ] ZINCRBY
- [ ] ZRANGE
- [ ] ZRANK
- [ ] ZREMRANGEBYRANK
- [ ] ZREMRANGEBYSCORE
- [ ] ZREM
- [ ] ZSCORE

### Hashes
- [ ] HGET
- [ ] HGETALL
- [ ] HSET
- [ ] HMSET
- [ ] HINCRBY

### HyperLogLog
- [ ] PFADD
- [ ] PFCOUNT

**Comment by Mordil** [comment]
This is no longer valid, as we rely on RediStack to provide the implementation.

For further requests, please file an issue against RediStack directly at https://gitlab.com/Mordil/RediStack
