### ISSUE TITLE
Redis Setup

### ISSUE THREAD

**Issue by mcdappdev** [vapor/redis#98]
Currently there is no way to setup Redis with a Keyed Session because that requires access to the `RedisClient`, which we don't have during the setup.

From the Slack:

> Ideally the keyed cache would take either a Future<Connection> to redis, or a connection pool

**Comment by pedantix** [comment]
Todo:

- implement  KeyedCacheSessions -  Devise prescriptive way to setup KeyedCacheSession 
https://github.com/vapor/vapor/blob/master/Sources/Vapor/Sessions/KeyedCacheSessions.swift

**Comment by tanner0101** [comment]
This will be getting cleaned up in the DatabaseKit 1.0.0 tag.
